import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../public/modern.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import BootstrapClientInit from "./BootstrapClientInit";
import Sidebar from "./components/Sidebar";
import SearchNavbar from "./components/SearchNavbar";
import { ThemeProvider } from "./theme-context";
import MatrixRain from "./components/MatrixRain";
import ThemeSwitcher from "./components/ThemeSwitcher";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-dark`}>
        <BootstrapClientInit />
        <ThemeProvider>
          <MatrixRain />
          <ThemeSwitcher />
          <SearchNavbar />
          <Sidebar />
          <div className="d-flex" style={{ minHeight: "100vh" }}>
            <main
              className="flex-grow-1 d-flex justify-content-center align-items-center glassy-scroll"
              style={{
                padding: "88px 0 32px 0",
                marginLeft: "250px",
                background: "transparent",
                minHeight: "100vh",
                width: '100vw',
                overflowY: 'auto',
                scrollbarWidth: 'thin',
              }}
            >
              {children}
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}